### PR TITLE
admin login

### LINKED ISSUE #29: Admin login
demo: https://wp.alithemes.com/html/jobbox/demos/dashboard/authentication.html

image

same with account but class is `User`

after login successfully, redirect admin to `/dashboard

image

Edit name of admin and email at below

### PR DESCRIPTION
**Pull request by dang-khai**
closed #29

### CODE REVIEW

**Comment by datlechin** [comment]
Chưa đúng yêu cầu.
Cần tạo ra một trang login mới riêng biệt dành cho admin
`/admin/login`

**Comment by datlechin** [comment]
@dang-khai do the same as demo in issue. Do not use account login view for admin

**Comment by datlechin** [comment]
@dang-khai do the same as demo in issue. Do not use account login view for admin

**Comment by dang-khai** [comment]
@datlechin  
if so must create controller for admin login à

**Comment by datlechin** [comment]
Đúng rồi

**Review by datlechin — APPROVED** [review]

**Pull request merged**
